using System;



namespace GameGlobal
{
    public enum FrameFunction
    {
        Browse,
        Jump,
        GetTroopLeader,
        GetOneArchitecture,
        GetCampaignMilitary,
        Architecture_PersonToTroop,
        Architecture_WorkingList,
        PersonTransfer,
        PersonConvene,
        GetConvinceSourcePerson,
        GetConvinceDestinationPerson,
        GetRewardPerson,
        GetRedeemCaptive,
        GetReleaseCaptive,
        GetStudySkillPerson,
        GetStudyTitlePerson,
        GetStudyTitle,
        GetStudyStuntPerson,
        GetStudyStunt,
        GetTrainingMilitary,
        GetTrainingPerson,
        GetNewMilitaryKind,
        GetRecruitmentMilitary,
        GetRecruitmentPerson,
        GetMergeMilitary,
        GetAutoCampaignMilitaries,
        GetBeMergedMilitaries,
        GetBeDisbandedMilitaries,
        GetLevelUpMilitaries,
        GetLevelUpMiliaryKind,
        GetNewCapital,
        GetFriendlyDiplomaticRelation,
        GetAllyDiplomaticRelation,
        GetEnhanceDiplomaticRelation,
        GetEnhanceDiplomaticRelationPerson,
        GetAllyDiplomaticRelationPerson,
        GetDenounceDiplomaticRelation,
        GetTruceDiplomaticRelation,
        GetQuanXiangDiplomaticRelation,//劝降
        GetQuanXiangDiplomaticRelationPerson,
        GetTruceDiplomaticRelationPerson,
        GetAttackDefaultKind,
        GetAttackTargetKind,
        GetCastDefaultKind,
        GetCastTargetKind,
        GetInformationKind,
        GetInformationPerson,
       // GetSpyPerson,
        GetDestroyPerson,
        GetInstigatePerson,
        GetGossipPerson,
        GetSearchPerson,
        GetJailBreakPerson,
        GetAssassinatePerson,
        GetAssassinatePersonTarget,
        GetFacilityToBuild,
        GetFacilityToDemolish,
        Transport,
        GetArchitectureList,
        GetSection,
        GetSectionToDemolish,
        GetSectionAIDetail,
        GetFaction,
        GetDiplomaticRelation,
        GetState,
        GetTroopershipMilitary,
        GetShortestRouteway,
        GetShortestNoWaterRouteway,
        GetConfiscateTreasure,
        GetAwardTreasure,
        GetAwardTreasurePerson,
        xuanzemeinv,
        chongxingmeinv,
        MoveFeizi,
        ReleaseFeizi,
        KillPerson,
        KillCaptive,
        MoveCaptive,
        ReleaseSelfPerson,
        PersonManualHire,
        SelectPrince,
        AutoCreatePerson,//自动生成野武将
        GetOfficerType,
       // DengYong,
        AppointMayor, //任命太守
        DismissOfficer, //遣散
        //AppointOfficer,//任命官员
        GetRecallablePerson,//罢免官员
        GetRecallableTitle,
        GetAppointableTitle,
        GetAppointPerson,
       // MilitaryTransfer, //运输编队
        GetTransferMilitary,//读取运输编队
        GetTransferArchitecture,
        GetInformationToStop,
        SelectLandLink,
        SelectWaterLink,
        SelectMarryablePerson,
        SelectMarryTo,
        SelectTrainableChildren,
        SelectTrainPolicy,
        GetGeDiDiplomaticRelation
    }
}

